version: "3.9"
services:
  GradientBoost :
    image: 24241702/GB_docker_bike:latest
    container_name : Grandient_Boost
    ports: 
      - "8000:8000"
    depends_on :
      - fastapi 
    networks : 
      - network_work
    volumes : 
      - ./log:/api/log
    environment : 
      - LOG=1
      
  RandomForest :
    image: 24241702/RF_docker_bike:latest
    container_name : Random_Forest
    ports: 
      - "8000:8000"
    depends_on :
      - fastapi 
    networks : 
      - network_work
    volumes : 
      - ./log:/api/log
    environment : 
      - LOG=1
networks : 
  network_work :